---
- name: Install Java 1.8
  yum: name=java-1.8.0-openjdk state=present

- name: Add tomcat group
  group: name=tomcat

- name: Add tomcat user
  user: name=tomcat group=tomcat home=/home/tomcat createhome=yes

- name: Create tomcat7 directory
  file:
    path: /home/tomcat
    state: directory

- name: Copy and unarchive the latest version of Apache Tomcat v7
  unarchive:
    src: /etc/Ansible-Web-Infra-Deploy/Ansible-Web-Infra-Deploy/apache-tomcat-7.0.90.zip
    copy: yes
    dest: /home/tomcat

- name: Copy all WARs to webapps 
  copy: src=webapps/ dest="/home/tomcat/apache-tomcat-7.0.90/webapps" 

- name: Ansible Insert multiple lines using blockinfile
  blockinfile:
    dest: /etc/profile
    block: |
      export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64
      export PATH=$JAVA_HOME/bin:$PATH
      export CATALINA_HOME=/home/tomcat/apache-tomcat-7.0.90
      export CATALINA_BASE=/home/tomcat/apache-tomcat-7.0.90
    
- name: Update profile
  shell: source /etc/profile

- name: Give tomcat permission to run.
  shell: chmod u+x *.sh
  args:
    chdir: /home/tomcat/apache-tomcat-7.0.90/bin/

- name: Start tomcat service
  shell: nohup /home/tomcat/apache-tomcat-7.0.90/bin/startup.sh



